Update upload_file and add new ways to upload
FTB-Gamepedia/mediawiki-rs pull request #5
Opened 2020-06-30 11:11 UTC by SizableShrimp

This pull request serves to update the `upload_file` method and add new ways to upload, like `upload_filekey` and `upload_url`.
I also added new parameters that exist in the API, like `ignorewarnings` and `text`.
These features were mainly added to allow adding categories for ftb-rs uploads and resuming an upload if warnings are present with a filekey.
*I also didn't test `upload_filekey` or `upload_url` as I assumed they worked since the base `Form` object is the same for all 3 methods with one extra field for each.*
Even though I made this PR, **I barely know Rust at all**, and I may have gone about something the wrong way. I request that both @retep998 and @xbony2 review this to make sure it conforms to the project and works soundly.
I also used IntelliJ IDEA + Rust plugin to code this as I am familiar with IntelliJ and its shortcuts. I used the auto-format feature, which may have changed things from the normal Rust conventions. Please let me know if I need to revert this formatting. I can also modify my auto-format settings for the project to conform to conventions in the future.

2020-06-30 11:38 UTC, retep998 requested changes
Formatting should be done by rustfmt or cargo fmt or some wrapper thereof and not IDE specific formatting.

2020-06-30 11:38 UTC, retep998 commented on .gitignore
> +/.idea
IDE specific gitignore things should go in your personal system gitignore.

2020-06-30 11:38 UTC, retep998 commented on Cargo.toml
> +version = "0.0.2"
The version should only be bumped when publishing a new version to crates.io

2020-07-02 02:00 UTC, SizableShrimp commented
I just removed the last static lifetime and double-checked the code. It seems fine to accept this PR now, and then I can create the PR for ftb-rs with these changes.

2020-07-02 02:12 UTC, xbony2 approved these changes

2020-08-14 05:29 UTC, SizableShrimp commented
it was fun, PR #5, maybe #6 will have better luck :)

2020-08-14 05:29 UTC, closed without merging

2020-08-16 03:42 UTC, xbony2 commented
Sad!

2020-08-20 08:54 UTC, retep998 commented
Outdated by https://github.com/FTB-Gamepedia/mediawiki-rs/commit/54b48419e8b9faa80fc3f55fb2d7a6f99b6ce638